name: votl-watchdog

services:
  wdvotl:
    image: fileeditor/votl-watchdog
    container_name: votl-watchdog
    volumes:
      - ./data:/opt/wdvotl/data
      - ./logs:/opt/wdvotl/logs
    pull_policy: every_12h
    restart: on-failure:2